apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: label-studio-app
  name: label-studio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio-app
  strategy: {}
  template:
    metadata:
      labels:
        app: label-studio-app
    spec:
      containers:
      - image: heartexlabs/label-studio:latest
        name: label-studio-app
        env:
        - name: DJANGO_DB
          value: default
        - name: POSTGRE_NAME
          value: comitiva_label_studio
        - name: POSTGRE_USER
          value: comitivaesperanca
        - name: POSTGRE_PASSWORD
          value: Pantanal123
        - name: POSTGRE_PORT
          value: "5432"
        - name: POSTGRE_HOST
          value: pantanaldev-dev.postgres.database.azure.com
        - name: JSON_LOG
          value: "1"
        - name: LABEL_STUDIO_PORT
          value: "9000"
        
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 9000 
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  name: comitiva-esperanca-label-studio-service
  labels:
    run: comitiva-esperanca-label-studio-service
spec:
  ports:
  - port: 80
    name: "labelstudio-app"
    targetPort: 9000
  
  selector:
    app: label-studio-app
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comitiva-esperanca-backend
  name: comitiva-esperanca-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comitiva-esperanca-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: comitiva-esperanca-backend
    spec:
      containers:
      - image: mfelipemota/comitivaesperanca-backend:main
        name: comitiva-esperanca-backend
        env:
        - name: ASPNETCORE_URLS
          value: http://+:5400
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 5400 
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: comitiva-esperanca-backend-service
  labels:
    run: comitiva-esperanca-backend-service
spec:
  ports:
  - port: 80
    targetPort: 5400
    protocol: TCP
  selector:
    app: comitiva-esperanca-backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comitiva-esperanca-api-predict
  name: comitiva-esperanca-api-predict
spec:
  replicas: 4
  selector:
    matchLabels:
      app: comitiva-esperanca-api-predict
  strategy: {}
  template:
    metadata:
      labels:
        app: comitiva-esperanca-api-predict
    spec:
      containers:
      - image: mfelipemota/comitivaesperanca-api-predict:latest
        name: comitiva-esperanca-api-predict
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 7000 
---
apiVersion: v1
kind: Service
metadata:
  name: comitiva-esperanca-api-predict-service
  labels:
    run: comitiva-esperanca-api-predict-service
spec:
  ports:
  - port: 80
    targetPort: 7000
    protocol: TCP
  selector:
    app: comitiva-esperanca-api-predict
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comitiva-esperanca-api-predict
  name: comitiva-esperanca-api-predict
spec:
  replicas: 4
  selector:
    matchLabels:
      app: comitiva-esperanca-api-predict
  strategy: {}
  template:
    metadata:
      labels:
        app: comitiva-esperanca-api-predict
    spec:
      containers:
      - image: mfelipemota/comitivaesperanca-api-predict:latest
        name: comitiva-esperanca-api-predict
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 7000 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: label-studio-app
  name: label-studio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio-app
  strategy: {}
  template:
    metadata:
      labels:
        app: label-studio-app
    spec:
      containers:
      - image: heartexlabs/label-studio:latest
        name: label-studio-app
        env:
        - name: DJANGO_DB
          value: default
        - name: POSTGRE_NAME
          value: comitiva_label_studio
        - name: POSTGRE_USER
          value: comitivaesperanca
        - name: POSTGRE_PASSWORD
          value: Pantanal123
        - name: POSTGRE_PORT
          value: "5432"
        - name: POSTGRE_HOST
          value: pantanaldev-dev.postgres.database.azure.com
        - name: JSON_LOG
          value: "1"
        - name: LABEL_STUDIO_PORT
          value: "9000"
        
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 9000 
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: label-studio-app-service
  labels:
    run: label-studio-app-service
spec:
  ports:
  - port: 80
    targetPort: 7000
    protocol: TCP
  selector:
    app: label-studio-app
  type: LoadBalancer